cmake -S ${SRCDIR}/qdp-jit -B ${BUILDDIR}/build_qdp-jit \
  -DCMAKE_INSTALL_PREFIX=${INSTALLDIR}/QDP-JIT \
  -DCMAKE_PREFIX_PATH="${INSTALLDIR}/libxml2;${INSTALLDIR}/llvm-project;${INSTALLDIR}/QMP;" \
  -DBUILD_SHARED_LIBS=ON \
  -DQDP_ENABLE_BACKEND=CUDA \
  -DCUDA_TOOLKIT_ROOT_DIR=/opt/apps/cuda/13.0.2/ \
  -DQDP_ENABLE_COMM_SPLIT_DEVICEINIT=ON \
  -DQDP_ENABLE_LLVM17=ON \
  -DQDP_PROP_OPT=OFF \
  -DQIO_ENABLE_PARALLEL_IO=ON \
  -DQIO_ENABLE_QMP_ROUTE=ON \
  -DQDP_BUILD_EXAMPLES=ON \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_CXX_LINKER=mpicxx \
  -DCMAKE_C_LINKER=mpicc \
  -DMPI_CXX_COMPILER=mpicxx \
  -DMPI_C_COMPILER=mpicc \
  -DCMAKE_CXX_FLAGS="${ARCHFLAGS}"
cmake --build ${BUILDDIR}/build_qdp-jit ${CMAKE_MAKE_OPTS}
cmake --install ${BUILDDIR}/build_qdp-jit
