cmake -S ${SRCDIR}/qdpxx -B ${BUILDDIR}/build_qdpxx \
  -DCMAKE_INSTALL_PREFIX=${INSTALLDIR}/QDPXX \
  -DCMAKE_PREFIX_PATH="${INSTALLDIR}/QMP;${INSTALLDIR}/libxml2" \
  -DBUILD_SHARED_LIBS=ON \
  -DMPIEXEC_MAX_NUMPROCS=64 \
  -DQDP_USE_HDF5=ON \
  -DQDP_USE_OPENMP=ON \
  -DQDP_USE_SSE3=ON \
  -DQIO_ENABLE_PARALLEL_IO=ON \
  -DQIO_ENABLE_QMP_ROUTE=ON \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DCMAKE_C_COMPILER=mpicc \
  -DQDP_LAYOUT=cb2 \
  -DCMAKE_CXX_FLAGS="-O3 -msse3"
cmake --build ${BUILDDIR}/build_qdpxx ${CMAKE_MAKE_OPTS}
cmake --install ${BUILDDIR}/build_qdpxx
